import Image from 'next/image';
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css';

const Home = () => {

    const toggleTheme = () => {
        console.log("toggle theme")
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Tom Heaton</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <div className="wrapper" style={{height: "100vh", padding: "10px"}}>
                    <div className="d-flex flex-row flex-wrap align-items-center justify-content-center">
                        <img id="theme-toggle" className="avatar btn" src="/avatar.jpg" alt="Tom Heaton" onClick={toggleTheme} />
                        <h1 className="m-2 name">Tom Heaton
                            <small className="text-muted">developer</small>
                        </h1>
                    </div>
                    <div>
                        <p className="lead m-2">
                            hey, I am an eighteen year old who likes to code things.
                        </p>
                    </div>
                    <div className="d-flex flex-wrap justify-content-center cards">
                        <div className="card m-2" style={{width: "18rem"}}>
                            <div className="card-body btn">
                                <br/>
                                <p>Watch this space to see it fill up with all the projects I am working on!</p>
                            </div>
                        </div>
                    </div>
                    <footer className="d-flex fixed-bottom justify-content-center">
                        <div className="wrapper-footer d-flex-col">
                            <div className="socials">
                                <a target="_blank" href="https://www.github.com/tomheaton" rel="noopener noreferrer">
                                    <i className="bi-github" aria-label="Github"/>
                                </a>
                                <a target="_blank" href="https://www.discord.com/users/325306360004739072" rel="noopener noreferrer">
                                    <i className="bi-discord" aria-label="Discord"/>
                                </a>
                                <a target="_blank" href="https://www.twitter.com/tomheaton_" rel="noopener noreferrer">
                                    <i className="bi-twitter" aria-label="Twitter"/>
                                </a>
                            </div>
                            <p className="copyright">&#169; Tom Heaton 2021</p>
                        </div>
                    </footer>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
)
}

export default Home;
